# Author:Jack
# Date:2018/5/23

menu = {
    'Beijing':{
        'Chaoyang':{
            'Guomao':{
                'CICC':{},
                'HP':{},
                'Zhada bank':{},
                'CCTV':{},
            },
            'Wangjing':{
                'Momo':{}
                'Bentch':{},
                '360':{},
            },
            'Sanlitun':{
                'YUIKU':{},
                'Apple':{},
            },
        },
        'Changping':{
            'Shahe':{
                'Laonanhai':{},
                'Ataibaozi':{},
            },
            'Tiantongyuan':{
                'Lianjia':{},
                'Woaiwojia':{},
            },
            'Huilongguan':{},
        },
        'Haidian':{
            'Wudaokou':{
                'Google':{},
                'Wangyi':{},
                'Sohu':{},
                'Sogou':{},
                'Kuaishou':{},
            },
            'Zhongguancun':{
                'Youku':{},
                'Iqiyi':{},
                'Qichezhijia':{},
                'Xindongfang':{},
                'QQ':{},
            },
        },
    },
    'Shanghai':{
        'Pudong':{
            'lujiazui':{
                'CICC':{},
                'GaoSheng':{},
                'Mogen':{},
            },
            'Waitan':{},
        },
        'Minhang':{},
    },
    'Shandong':{
        'Jinan':{},
        'Qingdao':{},
        'Dezhou':{
            'Laoling':{
                'Dingwuzhen':{},
            },
            'Pingyuan':{},
        },
    },
}